# Generated by Django 4.1.6 on 2023-04-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooddetails',
            name='details',
            field=models.CharField(max_length=600),
        ),
    ]
