# Generated by Django 4.1.6 on 2023-04-27 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_alter_fooddetails_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooddetails',
            name='image',
        ),
    ]
