# Generated by Django 4.1.6 on 2023-04-27 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_remove_fooddetails_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooddetails',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
