# Generated by Django 4.1.6 on 2023-04-27 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_fooddetails_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fooddetails',
            old_name='cals_per100grams',
            new_name='cals',
        ),
        migrations.RenameField(
            model_name='fooddetails',
            old_name='carbs_per100grams',
            new_name='carbs',
        ),
        migrations.RenameField(
            model_name='fooddetails',
            old_name='fats_per100grams',
            new_name='fats',
        ),
        migrations.RenameField(
            model_name='fooddetails',
            old_name='protein_per100grams',
            new_name='protein',
        ),
        migrations.AddField(
            model_name='fooddetails',
            name='cholesterol',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='fooddetails',
            name='fats_monounsaturated',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='fooddetails',
            name='fats_polyunsaturated',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='fooddetails',
            name='fats_saturated',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='fooddetails',
            name='fibre',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='fooddetails',
            name='potassium',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='fooddetails',
            name='salt',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='fooddetails',
            name='suger',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fooddetails',
            name='units',
            field=models.CharField(default=-1.0, max_length=200),
            preserve_default=False,
        ),
    ]
