# Generated by Django 4.1.6 on 2023-04-27 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0005_rename_cals_per100grams_fooddetails_cals_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooddetails',
            name='cholesterol',
        ),
        migrations.RemoveField(
            model_name='fooddetails',
            name='potassium',
        ),
        migrations.AddField(
            model_name='fooddetails',
            name='cholesterol_mg',
            field=models.DecimalField(decimal_places=2, default=-1.0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fooddetails',
            name='potassium_mg',
            field=models.DecimalField(decimal_places=2, default=-1.0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fooddetails',
            name='carbs',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='fooddetails',
            name='fats',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='fooddetails',
            name='fats_monounsaturated',
            field=models.DecimalField(decimal_places=2, default=-1.0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fooddetails',
            name='fats_polyunsaturated',
            field=models.DecimalField(decimal_places=2, default=-1.0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fooddetails',
            name='fats_saturated',
            field=models.DecimalField(decimal_places=2, default=-1.0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fooddetails',
            name='fibre',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='fooddetails',
            name='protein',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='fooddetails',
            name='salt',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='fooddetails',
            name='suger',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
