# Generated by Django 4.1.6 on 2023-04-30 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0008_alter_dailynutritionaldata_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailynutritionaldata',
            name='cals',
            field=models.IntegerField(),
        ),
    ]
