# Generated by Django 4.1.6 on 2023-04-30 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0009_alter_dailynutritionaldata_cals_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailynutritionaldata',
            old_name='date',
            new_name='date1',
        ),
    ]
