# Generated by Django 4.1.6 on 2023-04-30 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0010_rename_date_dailynutritionaldata_date1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailynutritionaldata',
            old_name='date1',
            new_name='date',
        ),
    ]
