# Generated by Django 4.1.6 on 2023-05-05 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0011_rename_date1_dailynutritionaldata_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('food_id', models.CharField(max_length=200)),
                ('food_name', models.CharField(max_length=200)),
                ('food_weight', models.IntegerField()),
                ('cals', models.IntegerField()),
                ('protein', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fats', models.DecimalField(decimal_places=2, max_digits=5)),
                ('carbs', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
