# Generated by Django 4.1.6 on 2023-05-05 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0013_historyfood_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyfood',
            name='carbs',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='historyfood',
            name='fats',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='historyfood',
            name='protein',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
